### ISSUE TITLE
Security issues, and more

### ISSUE THREAD

**Issue by sohsatoh** [Baw-Appie/KernBypass#4]
I have had the opportunity to speak to the original developers about this version and would like to point out a few things.

1. it should be clearly stated that it is unofficial.

This is not obligatory, but the original developer would like to see it.
We recommend changing the package name etc. to avoid conflicts with other versions and to make it easier for users to understand.

2. do not unsandbox your app
3. do not allow apps to use task_for_pid

These two can be major security risks. They also make KernBypass almost useless. This is at least a significant departure from the desired behaviour of the original version. (For example, it would allow apps to use functions such as fork() and exec(), which could be used to perform jailbreak detection).

**Comment by Baw-Appie** [comment]
1. It is obviously my mistake to clearly this as an unofficial build. After checking his tweet, he made corrections right away.
2. I have already changed the bundle ID of KernBypass for this version to com.rpgfarm.kernbypass because there was already confusion about the bundle ID for Kritanta and Axon.
3. This tweak unsandboxes the app and gives it access to task_for_pid.
But I don't think this a dangerous security issue. For example, checkra1n already unsandboxes the application.
4. fork(), exec() are not a problem. Just enable A-Bypass

**Comment by Baw-Appie** [comment]
I contacted GitHub support and removed everything related to version 0.1 from the repository.  Have a nice day!  🥰
